# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66c315341a5174c0a67bf960c963ba184643c5eb4ecd425a08eb011b89af976490d7ba20200312995020151ad78187825c9b4f599ae59ab3bc337218f4e5445a

test:
  secret_key_base: 529640cf602a70d7a487dc6bdc3409ed7f59960574473793a0596602695edc596f6a573ff0b58921e0c3e83b8365e89c98d0bd201147d809397bd934e015db50

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
